version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/curbmap-reactnative
    branches:
      only:
        - development
    steps:
      - checkout
      - run: yarn install --force
      - deploy:
          name: Exposing
          command:  |
            if [ "${CIRCLE_BRANCH}" == "development" ]; then
              exp login -u "${EXPOUSER}" -p "${EXPOPASS}" --non-interactive
              exp publish -s "curbmap@gmail.com"
            fi