version: 2
jobs:
  build:
    docker:
      - image: curbmap/fedora-node:v0.0.2
    working_directory: ~/curbmap-reactnative
    branches:
      only:
        - master
    steps:
      - checkout
      - run: yarn install --force
      - deploy:
          name: Exposing
          command:  |
              exp login -u "${EXPOUSER}" -p "${EXPOPASS}" --non-interactive
              exp publish -s "curbmap@gmail.com"
